---
title: "Deep Learning with Airborne Laser Scanning Data for Forest Inventories"
subtitle: "Tutorial"
author:
  - name: "Brent A. Murray"
    affiliation: "University of British Columbia – Integrated Remote Sensing Studio"
  - name: "Harry Seely"
    affiliation: "University of British Columbia – Integrated Remote Sensing Studio"
  - name: "Yuwei Cao"
    affiliation: "University of British Columbia – Integrated Remote Sensing Studio"
  - name: "Ahmed Ragab"
    affiliation: "Natural Resources Canada - CanmetENERGY;<br>Polytechnique Montreal - Department of Mathematics and Industrial Engineering"
format:
  html:
    toc: True
---

::: callout-important
This workshop website is still underdevelopment and the content will continue to change until the workshop takes place on February 5th, 2026.
:::

## Overview
This is an introductory workshop for deep learning techniques for Enhanced Forest Inventories (EFIs) presented at the Canadian Cross-Country EFI Checkup. This workshop covers a basic end-to-end deep learning workflow for EFI applications, covering an introduction into deep learning, to data preparation, and finally a demo of model training, evaluation, and deployment. There will also be some examples of real world forest inventory deep learning applications showcasing some of the possibilities there are with these techniques.

### You will learn
- What deep learning is and how it can be used for EFIs.
- How to prepare and read in data for use in deep learning.
- Basics of using the <a href="https://lightning.ai/docs/pytorch/stable/" target="_blank">PyTorch Lightning</a> deep learning library.
- Training a deep learning model for  species classification and biomass prediction tasks.
- Testing and evaluating deep learning models.

::: callout-note
This site will remain open after the workshop for participants to review the content or share it with others. Because deep neural networks often require long training times, all datasets, training outputs, and model evaluations have been precomputed and are provided as part of this tutorial. We encourage you to follow along with the workshop to ask and return to the site at a later time to run the code/examples.
:::

::: {.hero}
## Setup
To get ready for this workshop follow the links below.

[Get Started](setup.qmd){.btn .btn-primary} [View Schedule](schedule.qmd){.btn .btn-outline-primary}
:::

## Instructors
| Name | Affiliation |
|---|---|
| <a href="https://www.researchgate.net/profile/Brent-Murray-4" target="_blank">Brent A. Murray</a> | Integrated Remote Sensing Studio. University of British Columbia |
| <a href="https://www.researchgate.net/profile/Harry-Seely" target="_blank">Harry Seely</a> | Integrated Remote Sensing Studio. University of British Columbia |
| <a href="https://www.researchgate.net/profile/Yuwei-Cao-2?ev=hdr_xprf" target="_blank">Yuwei Cao</a> | Integrated Remote Sensing Studio. University of British Columbia |
| <a href="https://www.researchgate.net/profile/Ahmed-Ragab-17" target="_blank">Ahmed Ragab</a> | CanmetENERGY. Natural Resrouces Canada;<br>Department of Mathematics and Industrial Engineering. Polytechnique Montreal |