---
title: "Setup"
format:
  html:
    toc: True
---

## 1) Code 

Setup begins with downloading all the code from the GitHub repository. Open up a terminal in the folder where you intend to set up the project. You can download the codebase using git as follows in the terminal:

Clone the GitHub repository:

`git clone https://github.com/Brent-Murray/DeepLearningEFI`

Change to the repository directory:

`cd DeepLearningEFI`

## 2) Data

The preprocessed data can be downloaded **[here](https://doi.org/10.5281/zenodo.18420757)**. Ensure the data is stored in the same folder where your code is stored.

**For specific data preprocessing information, see the [Data Section](02_data.qmd)**

## 3) Python Environment Setup

**Environment setup is performed using the [uv package manager](https://docs.astral.sh/uv/) which will need to be installed to run the tutorial code.**

The uv package manager allows for the installation of specific package versions to maintain reproducibility. The list of packages and their versions is included in the [`pyproject.toml`](pyproject.toml) file.

**This code has been tested on Windows 11 and Ubuntu 24.04.2**

1. Install uv package manager by following the instructions at [https://docs.astral.sh/uv/getting-started/installation](https://docs.astral.sh/uv/getting-started/installation)

    On a Windows system, this can be done by running the following command in PowerShell:

    ```{.terminal}
    -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
    ```

    On a Linux or MacOS system, run the following command in the terminal:

    ```{.terminal}
    curl -LsSf https://astral.sh/uv/install.sh | sh
    ```

2. Open a terminal and check that uv is installed by running 

    ```{.terminal}
    uv --help
    ```

3. Ensure uv is up-to-date by running

    ```{.terminal}
    uv self update
    ```

4. Intialize the uv environment and install dependencies.

    ```{.terminal}
    uv sync
    ```

## 4) Directory structure

After downloading the data and setting up the python environment (see above), your directory structure should include the following (among other miscellaneous files):

* 01_intro.qmd
* 02_data.qmd
* 03_train.qmd
* 04_evaluation.qmd
* 05_examples.qmd
* compute_lidar_metrics.qmd
* data
* pyproject.toml
* random_forest.qmd
* schedule.qmd
* setup.qmd
* src
* uv.lock
* .venv